[package]
name = "snek"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
glfw = { version = "0.55.0", features = [ "image" ] }
image = { version = "0.24.9", features = [ "ico" ] }
rand = "0.8.5"
soloud = "1.0.5"

[build-dependencies]
gl_generator = "0.14.0"
winres = "0.1.12"
